Studiosity/grover

.travis.yml
CHANGELOG.md
README.md
grover.gemspec
lib/grover.rb
package.json

Also update the README to expand on direct use of Grover and caveats regarding relative paths

Add support for puppeteer debugging options

---

CHANGELOG.md
Gemfile
Rakefile
bin/console
grover.gemspec
lib/grover.rb
lib/grover/configuration.rb
lib/grover/html_preprocessor.rb
lib/grover/middleware.rb
lib/grover/utils.rb
lib/grover/version.rb
spec/grover/configuration_spec.rb
spec/grover/html_preprocessor_spec.rb
spec/grover/middleware_spec.rb
spec/grover/utils_spec.rb
spec/grover_spec.rb
spec/spec_helper.rb

See https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment

Add magic comment for freezing string literals

---

spec/grover_spec.rb

on my machine, one rspec test failed due to localisation. 
this improves the testing.

fix rspec test to avoid false error due to localisation of google response

---

README.md
lib/grover.rb
spec/grover_spec.rb

minor change + doc how to run heroku 
impact > likely small change to CI travis

Issue running on heroku

---

README.md
lib/grover.rb
spec/grover_spec.rb

Relates to #30, not sure if it will fix the issue though

Allow wait until option to be passed through to puppeteer

---

CHANGELOG.md
README.md
lib/grover.rb
spec/grover_spec.rb

Allow requesting URIs with basic authentication
Thanks to @rwtaylor: https://github.com/Studiosity/grover/compare/ad4d31ba5c1ccbaf7dcadd9c71544250e0cd39cd...rwtaylor:master

Add support for basic authentication

---

lib/grover.rb
spec/grover_spec.rb

Ensure viewport width and height are integers

---

README.md

- Separate sections for Middleware vs Direct Execution
- Resolves #56

Clarify cover page usage

---

README.md

Fix Puppeteer API documentation links

---

.rubocop.yml
.travis.yml
spec/grover/middleware_spec.rb
spec/grover_spec.rb

Update specs to comply with RSpec/StubbedMock

Fix rubocop call in travis.yml

---

grover.gemspec
lib/grover/processor.rb
spec/grover/processor_spec.rb

Catch a JSON::ParserError which is likely caused by OOM errors in the worker. 
Resolves #81
Resolves #82

Add handling of invalid worker responses

---

.travis.yml
grover.gemspec

Expand required Ruby version to allow v3.0

---

CHANGELOG.md
README.md
lib/grover/js/processor.js
spec/grover/processor_spec.rb

This PR adds support for addStyleTag and addScriptTag.
Also, My humble apologies for not attending to the comments in the original PR #71.

Support addStyleTag and addScriptTag

---

CHANGELOG.md
README.md
lib/grover.rb
lib/grover/js/processor.js
lib/grover/options_fixer.rb
lib/grover/utils.rb
package.json
spec/grover/processor_spec.rb
spec/grover/utils_spec.rb
spec/grover_spec.rb
spec/spec_helper.rb

* setUserAgent
* emulateMediaFeatures
* emulateTimezone
* emulateVisionDeficiency
* setBypassCSP
* setExtraHTTPHeaders
* setGeolocation
* waitForTimeout
* focus
* hover

Add support for various methods

---

.github/workflows/test.yml
package.json
spec/grover/processor_spec.rb

Include new puppeteer versions and a more expansive set of node versions

Update build matrix with newer versions

---

README.md

Include suggestion from @abrom to enable this on Heroku using 19+.

Include instructions for .cjs file for heroku

---

lib/grover.rb

Updated the `options` doc link

Puppeteer api link

---

.github/workflows/test.yml
grover.gemspec

Add Ruby 3.2 support

---

spec/grover/utils_spec.rb

Fix another lint

---

.rubocop.yml
Gemfile
grover.gemspec

Revert to `gemfile` for Gemspec/DevelopmentDependencies cop

---

README.md
lib/grover/js/processor.cjs
spec/grover/processor_spec.rb

closes https://github.com/Studiosity/grover/issues/268

Feature to specify 'evaluateOnNewDocument'

---

README.md

Added a new Troubleshooting section that can potentially be used for additional "gotchas" in the future.

Add troubleshooting section to README regarding automatic HTTPS upgrades.
