Studiosity/grover

grover.gemspec, lib/grover.rb, spec/grover_spec.rb
Use nokogiri instead of regexes for parsing out metadata (to deal with embedded HTML header/footer templates)
Fix bug where boolean/numeric type options not handled correctly when passed through meta tags
=> Fix bugs in handling of meta tag content (inline html templates)

.codeclimate.yml, .rubocop.yml, CHANGELOG.md, README.md, grover.gemspec, lib/active_support_ext/object/deep_dup.rb, lib/active_support_ext/object/duplicable.rb, lib/grover.rb, lib/grover/middleware.rb, lib/grover/utils.rb, spec/grover/middleware_spec.rb, spec/grover/utils_spec.rb, spec/grover_spec.rb
Because Puppeteer doesn't allow for the header/footer to be configured 'per page' on a programatic basis, instead we'll try overcome this by allowing the response PDF to have a specified page (or pages) added to the front and back.
The specified path will be requested via the middleware (to the downstream app) using the same request method/body as the original request, but will override the path/params with those specified in the `front_cover_path` and `back_cover_path` parameters.
These parameters can be configured in the global options or via meta tags in the original downstream response.
=> Add support for configuring a front and back cover page for PDFs

CHANGELOG.md, README.md, lib/grover/configuration.rb, lib/grover/middleware.rb, spec/grover/configuration_spec.rb, spec/grover/middleware_spec.rb, spec/grover_spec.rb
It looks like Rails speeds things up by re-using the rack objects and just sanitises them between requests. As such, we can't use any memoization (or we end up potentially using data from previous requests). Ouch!
=> Fix memoization bug

CHANGELOG.md, lib/grover.rb, package.json, spec/grover_spec.rb
If HTML content passed through contains any line starting with `http` the option parser was incorrectly identifying the source as a URL and thus not including those options
Update puppeteer development dependency to 1.16.0
=> Fix bug in meta-option parsing

README.md
Not sure if this is the right place to include these docs, or even if this should maybe be a method that's inserted into all Controllers (maybe through the middleware)?
I was experimenting with `wicked_pdf`, and it's pretty easy with that project to render a PDF of _any_ Rails view. This code does the same thing with Grover, it could be useful for others?
=> Add sample code to render a Rails view as PDF

README.md, spec/grover_spec.rb
For reasons unknown, Travis (linux) and Mac ruby platforms return different results for A3 page height. 
Change handles this by running a different spec depending on the platform
=> Add fix for weird page width difference between platforms

CHANGELOG.md, lib/grover.rb, lib/grover/utils.rb, spec/grover/html_preprocessor_spec.rb, spec/grover/utils_spec.rb, spec/grover_spec.rb
With Ruby 2.2 EOL in 2018, time to drop support. For Grover that just means we can use the squiggly heredoc
=> Drop support for Ruby 2.2

CHANGELOG.md, README.md, grover.gemspec, lib/grover.rb, spec/grover_spec.rb, spec/spec_helper.rb
Doesn't include middleware changes, for now just adding a way to call to the puppeteer `screenshot` method: https://github.com/GoogleChrome/puppeteer/blob/v1.18.1/docs/api.md#pagescreenshotoptions
Helper methods `to_png` and `to_jpeg` are also included
=> Add support for capturing PNG/JPEG screenshots

.rubocop.yml, CHANGELOG.md, README.md, lib/grover/configuration.rb, lib/grover/middleware.rb, spec/grover/middleware_spec.rb, spec/grover_spec.rb
Adds Rack middleware that identifies requests with PNG, JPEG or JPG extensions and calls the downstream app with the extension removed, then converts the resulting response to an image (if the response is HTML) - ie same as PDF requests. The default behaviour is for these requests to remain unchanged unless the app configuration enables them.
Adds ability to ignore requests based on path and pass them through the app without modification
=> Add PNG/JPEG conversion middleware

CHANGELOG.md, README.md, lib/grover.rb, spec/grover_spec.rb
Implements `page.setViewport` in the conversion process allowing configuration of page width/height,  and various other viewport options
=> Add ability to set `viewport` options

.rubocop.yml, CHANGELOG.md, README.md, grover.gemspec, lib/grover.rb, spec/grover_spec.rb
Launch parameters can be provided either by global configuration, instance initialisation or through meta tags.
For config and initialisation, recommended format would be an array of string parameters:
```
launch_params: ['--disable-speech-api', '--no-sandbox']
```
For meta tags it can be provided as a serialised array of strings:
```
<meta name="grover-launch_args" content="['--disable-speech-api', '--no-sandbox']" />
```
=> Allow launch param args to be provided via configuration/meta

.travis.yml, lib/grover.rb, package.json, spec/grover_spec.rb
Add support for new emulateMediaType in Puppeteer 2.0.0. See [Puppeteer v2.0.0 changelog](https://github.com/puppeteer/puppeteer/releases/tag/v2.0.0)
Update Travis config to test 1.x and 2.x of Puppeteer
=> Add support for new emulateMediaType in Puppeteer 2.0.0

CHANGELOG.md, README.md, lib/grover.rb, spec/grover_spec.rb
Based on work by @ryansmith23 https://github.com/Studiosity/grover/compare/8af71013f6076d0b5810599422271c6b75d9ca0d...epona-science:master
Allows for the executable path for Chrome/Chromium to be overridden via the `executable_path` option.
=> Add option for specifying custom executable path

README.md, lib/grover.rb, spec/grover_spec.rb
Allow script to be provided that is executed (evaluated) after the page has been rendered but before it is converted to PDF or image
=> Add script execution support

lib/grover/middleware.rb, spec/grover/middleware_spec.rb
Setting/updating instance variables in rack middleware is not thread safe. Please consider this a security issue since instance variable content could get mixed up between request threads, unintentionally sending someone else's response to a user.
See a similar issue with pdfkit: pdfkit/pdfkit#377
Also see: https://stackoverflow.com/questions/23028226/rack-middleware-and-thread-safety
=> Middleware thread safety

.rubocop.yml, CHANGELOG.md, lib/grover/middleware.rb, spec/grover/middleware_spec.rb
Fixes issue raised in #40 
The original request env was adding cached parameters resulting in the cover page requests using the cache instead of generating the params themselves. This change scrubs the env before calling to the app when generating the cover page. The method used was pulled out of the ActionController TestCase class so should give us reasonable expectations over what needs to be cleaned up between requests.
=> Scrub the middleware cover page request env before request

README.md, lib/grover.rb
Hi added the possibility to add cookies.
=> Adding setCookies option to a page instance

.rubocop.yml, .travis.yml, CHANGELOG.md, package.json, spec/grover_spec.rb
Update specs to support ImageMagick 7
Update Rubocop config to support latest cops
Include Puppeteer 3.x in CI build matrix
Bump minimum NodeJS version from CI default (8) to 10 - needed for Puppeteer 3.x
=> Update specs to support ImageMagick 7

.rubocop.yml, README.md, grover.gemspec, lib/grover.rb, lib/grover/errors.rb, lib/grover/js/processor.js, lib/grover/processor.rb, spec/active_support_ext/object/deep_dup_spec.rb, spec/grover/errors_spec.rb, spec/grover/middleware_spec.rb, spec/grover/options_builder_spec.rb, spec/grover/processor_spec.rb, spec/grover_spec.rb
There is a potential process leak style issue where successive calls to Schmooze will result in node processes being started and not being cleaned up. This also appears to have the side effect of the node process preventing regular Chrome from being able to quit due to some sort of shared memory mutex shared with Chromium that the node process is somehow holding on to. The process is not cleaned up due to how Schmooze uses the Ruby garbage collector to clean up the node process, which has been seen to potentially stick around for a considerable amount of time. If enough Grover instances were launched it would likely result in some sort of resource contention.
Given Grover instantiates a new instance of the Schmooze processor for each call, there is really no need for the node process to …
=> Remove Schmooze in favour of built in fork

README.md
Clarify documentation when running on Heroku by explicitly saying to install the node.js buildpack
Resolves #65
=> Add documentation for node buildpack in Heroku

.rubocop.yml, CHANGELOG.md, lib/grover/middleware.rb, spec/grover/middleware_spec.rb
I came across this situation this week, where I was loading a page that had javascript based  calendar which loaded additional resources. While the page loaded the JSON that populated the calendar did not because the AJAX calls to fetch data did not have the cookies it needed.
This just reuses the example of re-sending cookies, but it puts it into the middleware.
=> Ensure cookies from incoming request are passed to Grover via Middleware

CHANGELOG.md, lib/grover/processor.rb, package.json, spec/grover/processor_spec.rb
Fixes bug where problems occurring while launching the NodeJS process are masked by an error raised when trying to "close" the unassigned IO
Resolves #65
=> Fix bug masking NodeJS launch failures

CHANGELOG.md, README.md, lib/grover/js/processor.js, spec/grover/processor_spec.rb
Hi, is there any interest in merging this change? It just adds support for [waitForSelector](https://pptr.dev/#?product=Puppeteer&version=v4.0.0&show=api-pagewaitforselectorselector-options) which I needed on a recent project. Open to any feedback or changes needed.
=> Add waitForSelector support

.rubocop.yml, .travis.yml, CHANGELOG.md, README.md, grover.gemspec, lib/grover/middleware.rb, lib/grover/options_builder.rb, package.json, spec/grover/middleware_spec.rb
The issue manifested itself in the Capybara middleware, although it's possible to see the same issue elsewhere. In short, v3.30 of Capybara modified its middleware to track the request URIs instead of just the count. When the response came back it would remove the URI from the list of current requests. Unfortunately this would break when Grover modifies the URI. As a result Capybara would leave the request in it's list of current requests resulting in it thinking there was some long running request when in truth everything was fine!
Although the issue in the Capybara middleware [has been fixed](https://github.com/teamcapybara/capybara/pull/2378) it's safest to just have Grover restore the env (where possible/practical) once the downstream request has been fulfilled.
Also addressed:
Drop …
=> Fix bug in middleware where path/URI weren't restored after calling downstream

README.md
`combine_pdf` seems to be a proper [gem name](https://github.com/boazsegev/combine_pdf)
```
➜   gem install combine_pdfs
ERROR:  Could not find a valid gem 'combine_pdfs' (>= 0) in any repository
ERROR:  Possible alternatives: combine_pdf, compile_pdf
```
=> Update gem name for combining PDF files

README.md, lib/grover/configuration.rb, lib/grover/middleware.rb, spec/grover/configuration_spec.rb, spec/grover/middleware_spec.rb
Fixes #83
Closes #84 
Add `root_url` option available as either a configuration option for the middleware or as a global configuration option (middleware option taking precedence)
=> Add root_url option to middleware

lib/grover.rb, lib/grover/js/processor.js, spec/grover/processor_spec.rb, spec/grover_spec.rb
Resolves #94 
Handle `nil` input case by treating it as an empty string (convert all input to a string with `to_s`)
Handle empty string case in the processor by passing a single space to Puppeteer instead. Likely cause is that Puppeteer is taking an empty string to mean "not provided" and thus ignoring the call to `respond`, instead choosing to wait for further input.. which never comes:
https://github.com/puppeteer/puppeteer/blob/v5.5.0/docs/api.md#httprequestrespondresponse
=> Handle `nil` and empty string content edge-cases

CHANGELOG.md, README.md, lib/grover.rb, lib/grover/processor.rb, spec/grover/processor_spec.rb, spec/grover_spec.rb
This PR adds support to retrieve the HTML content. I just find it particularly helpful in debugging PDFs.
Let me know what you think about this 🙌 
FYI: https://github.com/puppeteer/puppeteer/pull/419
=> Add support to return the html content

.codeclimate.yml, README.md, grover.gemspec, lib/grover/js/processor.js, spec/grover/processor_spec.rb
Hi there! Grover has made our lives so much easier, thank you!
I'm hoping to add in a feature to allow PDF generation to fail when an asset fails to load. I've added a test and a line to the README. Any feedback or help getting this in would be greatly appreciated.
=> Feature: Add flag to fail to generate PDF if assets fail to load.

README.md, lib/grover/js/processor.js, spec/grover/processor_spec.rb
This PR adds support for waitForFunction & some relevant options.
My use case for this is when printing a page with Mapbox, it's good to wait until the map has loaded - there's not really a great way to handle this with the current wait variants. 
eg:
`page.waitForFunction("map.loaded()")`
I've added a couple of rspec tests for this functionality, and tested it properly on some pages with maps as well. Let me know if you have any thoughts!
=> Add waitForFunction support

lib/grover/js/processor.js
In puppeteer v10.2.0 they introduced changes to the way request interception handlers are processed:
- https://github.com/puppeteer/puppeteer/compare/v10.1.0...v10.2.0
- https://github.com/puppeteer/puppeteer/blob/c510df8d8e52fa361c26f6db011aaa9410c8996a/src/common/Page.ts#L627-L633
It caused a race condition in processing between two handlers (`page.once` and `page.on`). So I fixed this problem by properly awaiting response and disabling interception.
=> Fix #121: stylesheets/images rendering with puppeteer v10.2.0

lib/grover/js/processor.js, spec/grover/processor_spec.rb
Fixes the error in processor.js when using the vision_deficiency option as reported in issue #127.
Added a spec as you suggested, but I'm running into some strange behavior. On some test runs the mean_colour_statistics returns ["94", "71", "0"] (which I assume is correct) on other runs it returns ["240.506", "240.527", "242.569"]. This is likely the mean color from the page http://www.example.net/foo/bar. Do you recognize this inconsistency while running the specs?
```  
1) Grover::Processor#convert when converting to an image when vision deficiency is set to `deuteranopia` is expected to eq ["94", "71", "0"]
Failure/Error: it { expect(mean_colour_statistics(image)).to eq %w[94 71 0] }
expected: ["94", "71", "0"]
got: ["240.506", "240.527", "242.569"]
(compared using ==)
```
=> Fix error in processor.js when using the vision_deficiency option

.travis.yml, CHANGELOG.md, README.md, lib/grover/js/processor.js, package.json, spec/grover/processor_spec.rb
Puppeteer 10.4.0 added support for a PDF conversion timeout (default 30,000ms). This change will use the existing `timeout` option to apply to both the request and convert phases, but also adds `request_timeout` and `convert_timeout` options that can be used to overload `timeout`.
=> Add support for `request_timeout` and `convert_timeout` options

.rubocop.yml, .travis.yml, grover.gemspec
Ruby 3.1's release is around the corner and grover seems to work just fine with the Ruby 3.1.0-preview1. Specs all pass.
=> Ruby 3.1 compatibility

README.md
Hi 👋 
First off, thanks for the awesome work on that tool 💚 Love it so far, exactly what I was looking for.
This PR is just a small drive-by fix while reading the docs: The link to Puppeteer's documentation on PDF options was no longer working. I replaced it with a permalink to (what I think is) the respective document in the Puppeteer repo.
=> Update link to PDF options docs in README

spec/grover/processor_spec.rb
Heroku have killed off their free tier. Railway appears to be a suitable alternative.
=> Switch spec test cookie renderer app host from Heroku to Railway

.github/workflows/test.yml, .rubocop.yml, grover.gemspec, lib/active_support_ext/object/duplicable.rb, package.json, spec/active_support_ext/object/deep_dup_spec.rb, spec/grover/processor_spec.rb, spec/grover_spec.rb, spec/spec_helper.rb
Also remove Ruby 2.6 support
Fix new code lints
Update ActiveSupport Object extensions
Based in part on #170
=> Update development dependencies

lib/grover/js/processor.cjs
If not specified, the temporary user data directory is not cleaned up automatically. This can eventually result in the filesystem getting filled with puppeteer chrome profile files.
=> Clean up temporary user data directory

README.md
To protect my reputation, I will not mention how long it took before I realized `execute_script` is not a boolean option that causes JavaScript to run. Hopefully this PR clarifies the option a bit. Happy to improve the PR if my update is not completely accurate as to what `execute_script` will accept.
Thanks for your work on Grover! This is a huge improvement over our previous tool.
---
If you're curious, passing `true` to `execute_script` produces an error which can really lead you down a rabbit hole if you mistakenly assume it's a boolean:
```
/Users/david/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/grover-1.1.4/lib/grover/processor.rb:92:in `call_js_method': Protocol error (Runtime.callFunctionOn): Given expression does not evaluate to a function (Grover::JavaScript::ProtocolError) …
```
=> [readme] Clarify execute_script option

.github/workflows/test.yml, README.md, lib/grover/js/processor.cjs, spec/grover/processor_spec.rb, spec/spec_helper.rb
Idea taken from: https://github.com/Studiosity/grover/pull/115 from @drnic
---
Can be used with
```ruby
Grover.new(..., browser_ws_endpoint: "ws://localhost:3333")
```
and e.g. a `docker-compose.yaml` file like:
```yaml
version: "3.7"
services:
chrome:
image: browserless/chrome:1.57-puppeteer-19.2.2
ports:
- 3333:3000
```
Hopefully this PR is much easier to review and merge than the original one where I took the idea from.
We have been using this in a production system for a couple of months and haven't had any issues with this setup.
---
I can include an update to the docs with this PR as well, but I wasn't sure where exactly I should put this.
=> Implement remote browser option

README.md
I've noticed that some links in the Readme.md file that point to puppeteer documentation are broken. 
It seems it was affected by changes at this PR https://github.com/puppeteer/puppeteer/pull/9150, puppeteer team changed the documentation structure.
=> Update puppeteer documentation links

lib/grover/options_builder.rb
Fixed the newly failing lint that was blocking running tests.
Note that tests are still failing.  It looks like an issue with `https://cookierenderer-production.up.railway.app/`
=> Fix Rubocop lint

README.md
Back in October 2023, Browserless 2.0 came out:
https://github.com/browserless/browserless/pull/3345
The docker image is now hosted on github, and the WebSocket endpoint needs to be specified to `/chrome`
=> Updating Remote Chromium Docs to Reflect Browserless 2.x

README.md, lib/grover/configuration.rb, lib/grover/processor.rb, spec/grover/processor_spec.rb
We noticed that Chrome does not behave well with jemalloc enabled, and we prefer to use that in general. 
Instead of disabling jemalloc in the whole environment, we opted to just disable it for the node process used. Based on quick search, others have had the same issue as well (https://github.com/Studiosity/grover/issues/80)
We disabled it by passing a new environment variable for the node process like this
=> Enable passing environment variables to the node process

README.md, lib/grover.rb, lib/grover/configuration.rb, lib/grover/errors.rb, lib/grover/js/processor.cjs, lib/grover/middleware.rb, lib/grover/options_builder.rb, spec/fixtures/test.html, spec/grover/middleware_spec.rb, spec/grover/options_builder_spec.rb, spec/grover/processor_spec.rb, spec/grover_spec.rb, spec/spec_helper.rb
Puppeteer can load HTML from the local file system.
```
url = "file:///some/absolute/path/content.html"
pdf = Grover.new(url,
launch_args: [
'--no-sandbox',
'--disable-web-security',
'--disable-dev-shm-usage',
'--disable-setuid-sandbox',
'--allow-file-access-from-files',
'--enable-local-file-accesses'
],
wait_until: ['load', 'domcontentloaded'],
allow_file_url: true
).to_pdf
```
=> Allow loading html from file uri

.github/workflows/test.yml, lib/grover/js/processor.cjs, package.json
Puppeteer 23.x has switch from returning a `Buffer` to returning `Uint8Array` which has broken the result parsing in Grover. This wraps the convert action with `Buffer.from` (supports both `Buffer` and `Uint8Array`) to return a `Buffer` in a consistent way.
=> Add support for Puppeteer v23.x

.github/workflows/test.yml, README.md, lib/grover/errors.rb, lib/grover/js/processor.cjs, lib/grover/options_fixer.rb, lib/grover/processor.rb, lib/grover/utils.rb, spec/grover/configuration_spec.rb, spec/grover/processor_spec.rb, spec/grover/utils_spec.rb
When the `raise_on_js_error` option is set `true`, this raises a `Grover::JavaScript::PageRenderError` (containing the error messages both as a summary, as as an array (see `error_details` property) if there are any uncaught JS errors thrown when trying to render the page
=> Add raise_on_js_error option

README.md
Some `Grover.new` examples use (an old?) format for invocation where an explicit hash is the second argument. These fail because Grover expects keyword arguments.
=> Unwrap hash in Grover.new examples

Gemfile, README.md, grover.gemspec, lib/grover/configuration.rb, lib/grover/middleware.rb, lib/grover/processor.rb
Gem `combine_pdf` needed only for middleware and only for `front_cover` and/or `back_cover` functionality. This mean, that people which use grover directly by `display_url` or raw html need to have this gem as additional dependency. Problem, that `combine_pdf` contain as deps https://github.com/caiges/Ruby-RC4 , which is not supported any more (dead dependency). 
https://github.com/boazsegev/combine_pdf?tab=readme-ov-file#unmaintained---help-wanted - `combine_pdf` also unmaintained
Maintained solutions to use `pdfunite` cli from poppler library or to use https://hexapdf.gettalong.org/examples/merging.html (paid solution)
By this proposal I making `combine_pdf` as optional and not install as dependency, so developers, which need middleware and `front_cover` and/or `back_cover` …
=> Optional combine_pdf + support yarn pnp
